"""Context Oracle domain — BFS traversal, context bundle assembly, cache, search."""

from beadloom.context_oracle.builder import (
    bfs_subgraph,
    build_context,
    collect_chunks,
    suggest_ref_id,
)
from beadloom.context_oracle.cache import (
    CacheEntry,
    ContextCache,
    SqliteCache,
    build_context_cached,
    bundle_cache_key,
    compute_bundle_mtimes,
    compute_etag,
)
from beadloom.context_oracle.code_indexer import (
    LangConfig,
    check_parser_availability,
    clear_cache,
    extract_symbols,
    get_lang_config,
    parse_annotations,
    supported_extensions,
)
from beadloom.context_oracle.intent import (
    INTENT_DECLARED,
    INTENT_NONE_DECLARED,
    INTENT_NOT_CHECKED,
    MAX_DECLARATIONS,
    REASON_CONFIG_ERROR,
    REASON_NO_EPIC_DECLARES_ANY_NODE,
    REASON_NO_INTENT_DOCUMENTS,
    REASON_NOT_READ,
    DeclaredIntent,
    IntentReading,
    describe_intent_reason,
    select_intent,
)
from beadloom.context_oracle.search import has_fts5, populate_search_index, search_fts5

__all__ = [
    "INTENT_DECLARED",
    "INTENT_NONE_DECLARED",
    "INTENT_NOT_CHECKED",
    "MAX_DECLARATIONS",
    "REASON_CONFIG_ERROR",
    "REASON_NOT_READ",
    "REASON_NO_EPIC_DECLARES_ANY_NODE",
    "REASON_NO_INTENT_DOCUMENTS",
    "CacheEntry",
    "ContextCache",
    "DeclaredIntent",
    "IntentReading",
    "LangConfig",
    "SqliteCache",
    "bfs_subgraph",
    "build_context",
    "build_context_cached",
    "bundle_cache_key",
    "check_parser_availability",
    "clear_cache",
    "collect_chunks",
    "compute_bundle_mtimes",
    "compute_etag",
    "describe_intent_reason",
    "extract_symbols",
    "get_lang_config",
    "has_fts5",
    "parse_annotations",
    "populate_search_index",
    "search_fts5",
    "select_intent",
    "suggest_ref_id",
    "supported_extensions",
]
