"""Graph domain — YAML loader, diff, rule engine, import resolver, linter, snapshots."""

# beadloom:domain=graph

from beadloom.graph.diff import (
    EdgeChange,
    GraphDiff,
    NodeChange,
    compute_diff,
    compute_diff_from_snapshot,
    diff_to_dict,
    render_diff,
)
from beadloom.graph.import_resolver import (
    ImportInfo,
    create_import_edges,
    extract_imports,
    index_imports,
    resolve_import_to_node,
)
from beadloom.graph.linter import (
    LintError,
    LintResult,
    format_json,
    format_porcelain,
    format_rich,
    lint,
)
from beadloom.graph.loader import (
    DuplicateRefId,
    GraphLoadResult,
    NodeOrigin,
    ParsedFile,
    get_node_tags,
    load_graph,
    parse_graph_file,
    unique_by_ref_id,
    update_node_in_yaml,
)
from beadloom.graph.rule_engine import (
    CardinalityRule,
    DenyRule,
    NodeMatcher,
    RequireRule,
    Rule,
    Violation,
    evaluate_all,
    evaluate_cardinality_rules,
    evaluate_deny_rules,
    evaluate_require_rules,
    load_rules,
    validate_rules,
)
from beadloom.graph.snapshot import (
    SnapshotDiff,
    SnapshotInfo,
    compare_snapshots,
    list_snapshots,
    save_snapshot,
)

__all__ = [
    "CardinalityRule",
    "DenyRule",
    "DuplicateRefId",
    "EdgeChange",
    "GraphDiff",
    "GraphLoadResult",
    "ImportInfo",
    "LintError",
    "LintResult",
    "NodeChange",
    "NodeMatcher",
    "NodeOrigin",
    "ParsedFile",
    "RequireRule",
    "Rule",
    "SnapshotDiff",
    "SnapshotInfo",
    "Violation",
    "compare_snapshots",
    "compute_diff",
    "compute_diff_from_snapshot",
    "create_import_edges",
    "diff_to_dict",
    "evaluate_all",
    "evaluate_cardinality_rules",
    "evaluate_deny_rules",
    "evaluate_require_rules",
    "extract_imports",
    "format_json",
    "format_porcelain",
    "format_rich",
    "get_node_tags",
    "index_imports",
    "lint",
    "list_snapshots",
    "load_graph",
    "load_rules",
    "parse_graph_file",
    "render_diff",
    "resolve_import_to_node",
    "save_snapshot",
    "unique_by_ref_id",
    "update_node_in_yaml",
    "validate_rules",
]
