"""The reviewer's input: the change and the specification, not the author's account.

Public surface of the ``review-brief`` feature. Two decisions, kept apart because
they can be got wrong independently: :func:`assemble_brief` says what a reviewer
is handed, and :func:`release_notes` says when the author's account stops being
withheld.
"""

from beadloom.application.review_brief.assembly import assemble_brief
from beadloom.application.review_brief.models import (
    CHANNEL_BEAD_COMMENTS,
    CHANNEL_COMMIT_BODIES,
    CHANNEL_LAUNCH_PROMPT,
    CHANNEL_WORK_ITEM_DOCUMENTS,
    DEFEAT_NOTICE,
    FINDING_AMBIGUOUS_SCOPE,
    FINDING_NO_SCENARIO,
    FINDING_NO_SCOPE,
    FINDING_OUTSIDE_SCOPE,
    FINDING_UNKNOWN_REF,
    FINDING_UNMEASURED_CHANGE,
    RELEASE_CONDITION,
    WITHHELD_REASON,
    AuthorNote,
    BoundScenario,
    ChangedFile,
    Channel,
    Commit,
    Reachability,
    ReleaseOutcome,
    ReviewBrief,
    SpecDocument,
    WithheldNotes,
)
from beadloom.application.review_brief.reachability import (
    LAUNCH_PROMPT_REASON,
    UNNAMED_BEAD,
    UNREADABLE_CONFIG_REASON,
    bead_comments_channel,
    bead_comments_reason,
    commit_bodies_channel,
    launch_prompt_channel,
    prompts_naming_documents,
    reachability_of,
    work_item_documents_channel,
)
from beadloom.application.review_brief.release import (
    REFUSED_NO_VERDICT,
    SELF_RECORDED_VERDICT,
    UNNAMED_VERDICT_AUTHOR,
    VERDICT_MARKERS,
    release_notes,
    verdict_recorded,
)

__all__ = [
    "CHANNEL_BEAD_COMMENTS",
    "CHANNEL_COMMIT_BODIES",
    "CHANNEL_LAUNCH_PROMPT",
    "CHANNEL_WORK_ITEM_DOCUMENTS",
    "DEFEAT_NOTICE",
    "FINDING_AMBIGUOUS_SCOPE",
    "FINDING_NO_SCENARIO",
    "FINDING_NO_SCOPE",
    "FINDING_OUTSIDE_SCOPE",
    "FINDING_UNKNOWN_REF",
    "FINDING_UNMEASURED_CHANGE",
    "LAUNCH_PROMPT_REASON",
    "REFUSED_NO_VERDICT",
    "RELEASE_CONDITION",
    "SELF_RECORDED_VERDICT",
    "UNNAMED_BEAD",
    "UNNAMED_VERDICT_AUTHOR",
    "UNREADABLE_CONFIG_REASON",
    "VERDICT_MARKERS",
    "WITHHELD_REASON",
    "AuthorNote",
    "BoundScenario",
    "ChangedFile",
    "Channel",
    "Commit",
    "Reachability",
    "ReleaseOutcome",
    "ReviewBrief",
    "SpecDocument",
    "WithheldNotes",
    "assemble_brief",
    "bead_comments_channel",
    "bead_comments_reason",
    "commit_bodies_channel",
    "launch_prompt_channel",
    "prompts_naming_documents",
    "reachability_of",
    "release_notes",
    "verdict_recorded",
    "work_item_documents_channel",
]
