# beadloom:domain=onboarding
# beadloom:component=guard-hooks
"""Emitting the harness hook adapter that binds guards to a tool (BDL-061 S1).

A harness can run a command before an edit; Beadloom uses that to evaluate a
guard. The file written here is deliberately the thinnest thing that can work:

.. code-block:: sh

    exec beadloom guard "$1" --hook claude-code

**No logic in the adapter** is the rule the whole epic rests on. Anything the
script decided — which paths are exempt, how strict this project is, how to dig
a file path out of the event — would be behaviour that exists only inside one
tool, untested and unportable. Instead the event is forwarded verbatim and every
decision happens in the CLI, which is why a hook and a shell cannot disagree.

Registration is a **merge**, never a rewrite: an adopter's ``settings.json`` is
their file. Existing hooks (ours or anyone's) survive, re-running adds nothing,
and a file we cannot parse is reported and left untouched rather than replaced —
a scaffolder that eats a user's configuration is not worth the hook it installs.

The guard names are a parameter rather than an import: this module is in the
*onboarding domain*, and the registry lives in the application layer above it
(``architecture-layers``, severity ``error``). The CLI, which sits above both,
supplies them.
"""

from __future__ import annotations

import json
import stat
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Sequence

#: The emitted Claude Code hook adapter, relative to the project root.
GUARD_HOOK_RELPATH = Path(".claude") / "hooks" / "beadloom-guard.sh"

#: The Claude Code project settings file the adapter is registered in.
SETTINGS_RELPATH = Path(".claude") / "settings.json"

#: Hook event the guards are bound to (fires before a tool call).
HOOK_EVENT = "PreToolUse"

#: Tools whose invocation counts as "an edit is about to happen".
EDIT_MATCHER = "Edit|Write|MultiEdit|NotebookEdit"

_HOOK_SCRIPT = '''\
#!/bin/sh
# Generated by `beadloom setup-agentic-flow`. Do not edit.
#
# This adapter contains NO logic: it forwards the harness hook event to the
# Beadloom CLI, which owns every decision. Configure guards, strictness per work
# kind, and exclusions in `.beadloom/flow.yml`.
#
# Exit codes this adapter can return: 0 = pass/skip, 1 = warn (shown, never
# blocking), 2 = block, or error — the guard could not answer, so the edit stops.
# A defect in `.beadloom/flow.yml` or in the command line arrives as 2 here too.
# Run the same command without `--hook` and it exits 3 instead, which keeps a
# broken configuration distinguishable from a guard that fired; through a hook
# that distinction would only mean "the edit went through unguarded".
exec beadloom guard "$1" --hook claude-code
'''


@dataclass
class GuardHookResult:
    """What :func:`scaffold_guard_hooks` wrote."""

    script: Path | None = None
    guards_registered: list[str] = field(default_factory=list)
    guards_already_registered: list[str] = field(default_factory=list)
    settings_skipped_reason: str = ""


def hook_command(guard_name: str) -> str:
    """The settings command invoking the adapter for *guard_name*.

    ``$CLAUDE_PROJECT_DIR`` keeps the entry independent of the shell's working
    directory, which is not the project root for every tool invocation.
    """
    posix = GUARD_HOOK_RELPATH.as_posix()
    return f'"$CLAUDE_PROJECT_DIR"/{posix} {guard_name}'


def _write_script(project_root: Path) -> Path:
    """Write the adapter and make it executable."""
    path = project_root / GUARD_HOOK_RELPATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_HOOK_SCRIPT, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return path


def _load_settings(path: Path) -> dict[str, object] | None:
    """Parse the settings file; ``None`` when it exists but cannot be read as an object."""
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if not isinstance(data, dict):
        return None
    return data


def _existing_commands(entries: list[object]) -> set[str]:
    """Every command string already registered under the hook event."""
    commands: set[str] = set()
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        for hook in entry.get("hooks", []) or []:
            if isinstance(hook, dict) and isinstance(hook.get("command"), str):
                commands.add(hook["command"])
    return commands


def _register(
    settings: dict[str, object], guard_names: Sequence[str]
) -> tuple[list[str], list[str]]:
    """Add a hook entry per guard that is not registered yet (in place)."""
    hooks = settings.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        msg = "settings 'hooks' is not an object"
        raise ValueError(msg)
    entries = hooks.setdefault(HOOK_EVENT, [])
    if not isinstance(entries, list):
        msg = f"settings 'hooks.{HOOK_EVENT}' is not a list"
        raise ValueError(msg)

    present = _existing_commands(entries)
    added: list[str] = []
    already: list[str] = []
    for name in guard_names:
        command = hook_command(name)
        if command in present:
            already.append(name)
            continue
        entries.append(
            {
                "matcher": EDIT_MATCHER,
                "hooks": [{"type": "command", "command": command}],
            }
        )
        added.append(name)
    return added, already


def scaffold_guard_hooks(
    project_root: Path, *, guard_names: Sequence[str]
) -> GuardHookResult:
    """Write the adapter and register one hook entry per guard.

    Idempotent: re-running rewrites the (deterministic) script and adds only the
    entries that are missing. A settings file that cannot be parsed is left
    exactly as it is, with the reason reported in the result.
    """
    result = GuardHookResult()
    if not guard_names:
        return result
    result.script = _write_script(project_root)

    settings_path = project_root / SETTINGS_RELPATH
    settings = _load_settings(settings_path)
    if settings is None:
        result.settings_skipped_reason = (
            f"{SETTINGS_RELPATH.as_posix()} is not readable as JSON — left "
            "untouched; add the hook entries by hand or move the file aside"
        )
        return result
    try:
        added, already = _register(settings, guard_names)
    except ValueError as exc:
        result.settings_skipped_reason = (
            f"{SETTINGS_RELPATH.as_posix()}: {exc} — left untouched"
        )
        return result

    result.guards_registered = added
    result.guards_already_registered = already
    if added:
        settings_path.parent.mkdir(parents=True, exist_ok=True)
        settings_path.write_text(
            json.dumps(settings, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
    return result
