# beadloom:domain=onboarding
# beadloom:feature=role-adapters
"""Generate per-tool role adapters from composed roles (BDL-052 S3).

The role configurator's output stage: given a :class:`FlowConfig`, compose each
role (CORE + architecture + stack overlays) once and write a **per-tool adapter
set** for every configured tool:

* ``claude`` → ``.claude/agents/<role>.md`` (the Claude-Code subagent files).
  The slash-command set (``.claude/commands/*``) is vendored separately by
  :mod:`beadloom.onboarding.agentic_flow_setup` and is not regenerated here.
* ``cursor`` → ``.cursor/agents/<role>.md`` (Cursor subagents — same composed
  body) plus a thin ``.cursor/rules/beadloom-flow.md`` orchestrator pointer
  (the coordinator-as-Cursor-mode entry point).

Every adapter body is exactly ``compose_role(...)`` for the repo's ``flow.yml``,
so :func:`generate_adapters` is the single writer the drift-guard test verifies
against: a hand-edit of any adapter, or a CORE/overlay change without
regenerating, makes the on-disk file differ from the recomputed composition and
fails the guard.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

from beadloom.onboarding.role_composer import ROLE_NAMES, compose_all_roles

if TYPE_CHECKING:
    from beadloom.onboarding.flow_config import FlowConfig

#: Where each tool's composed role files live, relative to the project root.
TOOL_AGENT_DIRS: dict[str, Path] = {
    "claude": Path(".claude") / "agents",
    "cursor": Path(".cursor") / "agents",
}

#: The Cursor orchestrator-mode pointer (coordinator entry for Cursor).
_CURSOR_RULES_RELPATH = Path(".cursor") / "rules" / "beadloom-flow.md"

_CURSOR_RULES_BODY = """\
# Beadloom agentic flow (Cursor orchestrator mode)

Cursor runs the SAME flow as Claude Code, at parity: a coordinator orchestrates
`dev` / `test` / `review` / `tech-writer` subagents (declared in
`.cursor/agents/*.md`) in waves, then runs the Beadloom Gate (`beadloom ci`) and
loops the tech-writer on drifted refs until the Gate is green.

- Roles: see `.cursor/agents/{dev,test,review,tech-writer}.md` (composed from
  this repo's `.beadloom/flow.yml`: CORE + architecture + stack overlays).
- Orchestration: launch the four roles as Cursor subagents (own context/tools/
  model; foreground for review gates, background for parallel dev/test waves).
- Enforcement is tool-agnostic: the Beadloom Gate (`beadloom ci`) is the single
  source of truth, identical on Claude Code and Cursor.

This file is generated by `beadloom setup-agentic-flow` — re-run it (or
`beadloom config-check --fix`) after changing `.beadloom/flow.yml`. Do not edit
by hand; the drift-guard will flag divergence.
"""


@dataclass
class AdapterResult:
    """Files written per tool by :func:`generate_adapters`.

    ``agents`` maps a tool name to the project-relative role-file paths written;
    ``extra`` lists any non-role files (e.g. the Cursor orchestrator pointer).
    """

    agents: dict[str, list[str]] = field(default_factory=dict)
    extra: list[str] = field(default_factory=list)


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def cursor_rules_relpath() -> Path:
    """Project-relative path of the Cursor orchestrator-mode pointer."""
    return _CURSOR_RULES_RELPATH


def cursor_rules_body() -> str:
    """The generated Cursor orchestrator-mode pointer body."""
    return _CURSOR_RULES_BODY


def generate_adapters(config: FlowConfig, project_root: Path) -> AdapterResult:
    """Compose roles for ``config`` and write each configured tool's adapter set.

    For every tool in ``config.tools`` writes ``<tool-agent-dir>/<role>.md`` with
    the composed body, plus the Cursor orchestrator pointer when ``cursor`` is
    configured. Idempotent — the bytes depend only on ``config`` + the overlay
    sources, so re-running with the same config rewrites identical files.
    Returns an :class:`AdapterResult` of the project-relative paths written.
    """
    composed = compose_all_roles(config)
    result = AdapterResult()
    for tool in config.tools:
        agent_dir = TOOL_AGENT_DIRS[tool]
        written: list[str] = []
        for role in ROLE_NAMES:
            relpath = agent_dir / f"{role}.md"
            _write(project_root / relpath, composed[role])
            written.append(str(relpath))
        result.agents[tool] = written
    if "cursor" in config.tools:
        _write(project_root / _CURSOR_RULES_RELPATH, _CURSOR_RULES_BODY)
        result.extra.append(str(_CURSOR_RULES_RELPATH))
    return result
