"""Agent-config file generation: MCP config, IDE rules, and AGENTS.md."""

# beadloom:domain=onboarding
# beadloom:feature=agent-prime

from __future__ import annotations

import json
from typing import TYPE_CHECKING

import yaml

from beadloom.onboarding.scanner.rules_gen import _detect_rule_type

if TYPE_CHECKING:
    from pathlib import Path

# MCP config paths per editor (mirrors _MCP_TOOL_CONFIGS in cli.py).
_MCP_EDITOR_MARKERS: tuple[tuple[str, str], ...] = (
    (".cursor", "cursor"),
    (".windsurfrules", "windsurf"),
    (".claude", "claude-code"),
    ("CLAUDE.md", "claude-code"),
)

_MCP_DEFAULT_EDITOR = "claude-code"


def setup_mcp_auto(project_root: Path) -> str | None:
    """Auto-detect editor and create MCP config.

    Returns editor name on success, or *None* if config already exists.
    """
    import shutil

    # Detect editor (most specific marker first).
    editor = _MCP_DEFAULT_EDITOR
    for marker, name in _MCP_EDITOR_MARKERS:
        if (project_root / marker).exists():
            editor = name
            break

    # Resolve MCP config path.
    from pathlib import Path as _Path

    paths: dict[str, Path] = {
        "claude-code": project_root / ".mcp.json",
        "cursor": project_root / ".cursor" / "mcp.json",
        "windsurf": _Path.home() / ".codeium" / "windsurf" / "mcp_config.json",
    }
    mcp_path = paths[editor]

    # Never overwrite existing config.
    if mcp_path.exists():
        return None

    mcp_path.parent.mkdir(parents=True, exist_ok=True)

    beadloom_cmd = shutil.which("beadloom") or "beadloom"
    args: list[str] = ["mcp-serve"]
    if editor == "windsurf":
        args.extend(["--project", str(project_root.resolve())])

    data = {
        "mcpServers": {
            "beadloom": {
                "command": beadloom_cmd,
                "args": args,
            }
        }
    }

    mcp_path.write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return editor


# IDE rules adapter template — thin pointer to AGENTS.md.
_RULES_ADAPTER_TEMPLATE = """\
# Generated by Beadloom — do not edit manually
# See .beadloom/AGENTS.md for the source of truth

Read the file .beadloom/AGENTS.md before starting any work on this project.
It contains architecture rules, available MCP tools, and coding conventions.
"""

# Markers that identify a file as a beadloom-generated adapter.
_BEADLOOM_ADAPTER_MARKERS = ("beadloom", ".beadloom/AGENTS.md")

# IDE rules file paths and detection markers.
_RULES_CONFIGS: dict[str, dict[str, str]] = {
    "cursor": {
        "path": ".cursorrules",
        "marker": ".cursor",
    },
    "windsurf": {
        "path": ".windsurfrules",
        "marker": ".windsurfrules",
    },
    "cline": {
        "path": ".clinerules",
        "marker": ".clinerules",
    },
}


def _is_beadloom_adapter(path: Path) -> bool | None:
    """Check whether *path* contains beadloom adapter content.

    Returns ``True`` if the file is a beadloom adapter, ``False`` if
    it contains unrelated content, or ``None`` if the file cannot be read.
    """
    try:
        content = path.read_text(encoding="utf-8").lower()
    except (OSError, UnicodeDecodeError):
        return None
    return any(marker in content for marker in _BEADLOOM_ADAPTER_MARKERS)


def setup_rules_auto(project_root: Path) -> list[str]:
    """Auto-detect IDEs and create adapter files.

    Adapter files are thin pointers that tell the AI agent
    to read .beadloom/AGENTS.md before starting work.

    Content-aware logic:

    - File does not exist -> create adapter.
    - File exists and is a beadloom adapter -> update (safe overwrite).
    - File exists with non-beadloom content -> skip (user content).
    - File exists but unreadable -> skip (graceful degradation).

    Returns list of created/updated file names.
    """
    created: list[str] = []

    for _ide, cfg in _RULES_CONFIGS.items():
        marker_path = project_root / cfg["marker"]
        rules_path = project_root / cfg["path"]

        if not marker_path.exists():
            continue

        if rules_path.exists():
            is_ours = _is_beadloom_adapter(rules_path)
            if is_ours is True:
                # Our adapter — safe to update.
                rules_path.write_text(_RULES_ADAPTER_TEMPLATE, encoding="utf-8")
                created.append(cfg["path"])
            # is_ours is False (user content) or None (unreadable) — skip.
        else:
            # File doesn't exist — create new adapter.
            rules_path.write_text(_RULES_ADAPTER_TEMPLATE, encoding="utf-8")
            created.append(cfg["path"])

    return created


_AGENTS_MD_TEMPLATE_V2 = """\
# Beadloom — Agent Instructions

> Auto-generated by `beadloom init`. Safe to edit.
> Sections below `## Custom` are preserved on regeneration.

## Before starting work

- Call MCP tool `prime` to get current project context
- Or run `beadloom prime` in terminal
- For specific feature/domain: `beadloom ctx <ref-id>` or MCP `get_context(ref_id)`
- Search the codebase: `beadloom search "<query>"`
- If no ref_id is given: `list_nodes()` to discover the graph

## After changing code

1. `beadloom reindex` — update the index
2. `beadloom sync-check` — check for stale docs
3. If stale: update docs, then `beadloom reindex` again
4. `beadloom lint --strict` — verify architecture boundaries

## Conventions

- Feature IDs: DOMAIN-NNN (e.g., AUTH-001)
- Annotations: `# beadloom:feature=REF_ID` in code files
- Documentation: `docs/` directory
- Graph YAML: `.beadloom/_graph/`

## Available MCP Tools

{mcp_tools_section}
{rules_section}## Custom

<!-- beadloom:custom-start -->
<!-- Add project-specific instructions below this line -->
<!-- beadloom:custom-end -->
"""


def _build_mcp_tools_section() -> str:
    """Build the MCP tools table from the canonical catalog.

    Enumerates the single-source-of-truth ``MCP_TOOL_CATALOG`` so the
    documented tool count can never drift from the live registry
    (BDL-UX-Issues #93).
    """
    from beadloom.infrastructure.mcp_tools import MCP_TOOL_CATALOG

    lines = ["| Tool | Description |", "|------|-------------|"]
    for entry in MCP_TOOL_CATALOG:
        lines.append(f"| `{entry.name}` | {entry.summary} |")
    return "\n".join(lines)


def _build_rules_section(project_root: Path) -> str:
    """Build architecture rules section from rules.yml for AGENTS.md."""
    rules_path = project_root / ".beadloom" / "_graph" / "rules.yml"
    if not rules_path.exists():
        return ""

    data = yaml.safe_load(rules_path.read_text(encoding="utf-8"))
    if not data or not data.get("rules"):
        return ""

    lines = ["## Architecture Rules\n"]
    for rule in data["rules"]:
        name = rule.get("name", "unnamed")
        description = rule.get("description", "")
        rule_type = _detect_rule_type(rule)
        if description:
            lines.append(f"- **{name}** ({rule_type}): {description}")
        else:
            lines.append(f"- **{name}** ({rule_type})")
    lines.append("")
    return "\n".join(lines) + "\n"


def _extract_agents_custom_content(agents_path: Path) -> str:
    """Extract preserved user content from an existing AGENTS.md (if any)."""
    custom_start = "<!-- beadloom:custom-start -->"
    custom_end = "<!-- beadloom:custom-end -->"
    legacy_comment = "<!-- Add project-specific instructions below this line -->"

    custom_content = ""
    if agents_path.exists():
        text = agents_path.read_text(encoding="utf-8")

        sidx = text.find(custom_start)
        eidx = text.find(custom_end)
        if sidx != -1 and eidx != -1 and eidx > sidx:
            # New-format: extract between the two markers (exclusive).
            custom_content = text[sidx + len(custom_start) : eidx]
        else:
            # Legacy fallback: look for old HTML comment, then ## Custom.
            cidx = text.find(legacy_comment)
            if cidx != -1:
                custom_content = text[cidx + len(legacy_comment) :]
            else:
                hidx = text.find("## Custom")
                if hidx != -1:
                    custom_content = text[hidx + len("## Custom") :]

    # Strip the legacy comment from preserved content so it is not
    # duplicated inside the new markers (template already includes it).
    return custom_content.replace(legacy_comment, "").strip()


def build_agents_md_content(project_root: Path) -> str:
    """Render the full ``.beadloom/AGENTS.md`` content in memory.

    Pure builder: does not touch disk except to read the existing file's
    preserved custom block.  Shared by :func:`generate_agents_md` (which
    writes it) and the AgentConfigAsCode drift checker (which diffs it),
    guaranteeing a single source of truth for the generated content.
    """
    custom_start = "<!-- beadloom:custom-start -->"
    custom_end = "<!-- beadloom:custom-end -->"
    legacy_comment = "<!-- Add project-specific instructions below this line -->"

    agents_path = project_root / ".beadloom" / "AGENTS.md"
    custom_content = _extract_agents_custom_content(agents_path)

    rules_section = _build_rules_section(project_root)
    mcp_tools_section = _build_mcp_tools_section()
    content = _AGENTS_MD_TEMPLATE_V2.format(
        rules_section=rules_section,
        mcp_tools_section=mcp_tools_section,
    )

    if custom_content:
        placeholder = f"{custom_start}\n{legacy_comment}\n{custom_end}"
        replacement = f"{custom_start}\n{custom_content}\n{custom_end}"
        content = content.replace(placeholder, replacement)

    return content


def generate_agents_md(project_root: Path) -> Path:
    """Generate .beadloom/AGENTS.md with agent instructions.

    Preserves user content between ``<!-- beadloom:custom-start -->`` and
    ``<!-- beadloom:custom-end -->`` markers on regeneration.  Old-format
    files using only ``## Custom`` / the legacy HTML comment are migrated
    automatically.

    Returns the path to the generated file.
    """
    beadloom_dir = project_root / ".beadloom"
    beadloom_dir.mkdir(parents=True, exist_ok=True)
    agents_path = beadloom_dir / "AGENTS.md"

    content = build_agents_md_content(project_root)
    agents_path.write_text(content, encoding="utf-8")
    return agents_path
